spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    username:
    password:
  jpa:
    database: mysql
covid-main-url: http://openapi.data.go.kr/openapi/service/rest/Covid19/getCovid19SidoInfStateJson
covid-main-key:
location-url: https://maps.googleapis.com/maps/api/geocode/json
location-key:
convert-WGS84-to-TM-auth-url: https://sgisapi.kostat.go.kr/OpenAPI3/auth/authentication.json
convert-WGS84-to-TM-auth-id:
convert-WGS84-to-TM-auth-key:
convert-WGS84-to-TM-url: https://sgisapi.kostat.go.kr/OpenAPI3/transformation/transcoord.json
microdust-main-url: http://apis.data.go.kr/B552584/ArpltnInforInqireSvc/getMsrstnAcctoRltmMesureDnsty
microdust-main-key:
microdust-station-url: http://apis.data.go.kr/B552584/MsrstnInfoInqireSvc/getNearbyMsrstnList
specific-address-url: https://dapi.kakao.com/v2/local/geo/coord2regioncode.json
specific-address-key:
microdust-day-url: https://api.waqi.info/feed/
microdust-day-key:
